kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      group_by: ['alertname', 'priority']
      receiver: slack_demo
      routes:
      - match:
          severity: slack
        receiver: slack_demo
 
    receivers:
    - name: slack_demo
      slack_configs:
      - api_url: <insert_slack_webhook>
        channel: '#devops'
        